import Head from "next/head";
import { Inter } from "next/font/google";
import { useTranslation } from 'react-i18next'
import Button from '@mui/material/Button';
import { useState } from "react";
import { useRouter } from 'next/navigation';

const inter = Inter({ subsets: ["latin"] });

export default function Home() {

  const router = useRouter();

  const { 
    t,
    i18n: { changeLanguage, language} 
  } = useTranslation();

  const [currentLanguage, setCurrentLanguage ] = useState(language);

  const handleChangeLanguage = () => {
    const newLanguage = currentLanguage === 'en' ? 'pt' : 'en';
    changeLanguage(newLanguage);
    setCurrentLanguage(newLanguage);
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={`${inter.className} ${'h100'} ${'horizontalCenter'} ${'verticalCenter'}`}>
          <Button variant="contained" onClick={handleChangeLanguage}>{t('changeLanguage')}</Button>
          <Button variant="contained" onClick={() => router.push('/login-type')}>LOGIN</Button>
      </div>
    </>
  );
}
